# Generated by Django 5.1.1 on 2024-09-17 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fish_name", models.CharField(max_length=255, verbose_name="ชื่อปลา")),
                ("species", models.CharField(max_length=255, verbose_name="สายพันธ์ุ")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "เพศผู้"),
                            ("F", "เพศเมีย"),
                            ("U", "ไม่ทราบเพศ"),
                        ],
                        default="U",
                        max_length=1,
                        verbose_name="เพศ",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="วันเกิด")),
                ("description", models.TextField(verbose_name="รายละเอียด")),
                ("size", models.FloatField(verbose_name="ขนาด")),
                (
                    "image",
                    models.ImageField(
                        upload_to="media/fishimage", verbose_name="รูปปลา"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_type",
                    models.CharField(max_length=255, verbose_name="ประเภทอาหาร"),
                ),
                (
                    "food_name",
                    models.CharField(max_length=255, verbose_name="ชื่ออาหาร"),
                ),
                (
                    "feeding_frequency",
                    models.IntegerField(verbose_name="ความถี่ในการให้อาหาร"),
                ),
                (
                    "fish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.fish",
                        verbose_name="ปลา",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Habitat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "habitat_name",
                    models.CharField(max_length=255, verbose_name="ชื่อแหล่งที่อยู่"),
                ),
                ("temperature", models.FloatField(verbose_name="อุณหภูมิ")),
                (
                    "ph_level",
                    models.FloatField(verbose_name="ค่าความเป็นกรด-ด่าง (pH)"),
                ),
                (
                    "fish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.fish",
                        verbose_name="ปลา",
                    ),
                ),
            ],
        ),
    ]
