# Generated by Django 5.1.1 on 2024-09-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_habitat_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habitat",
            name="migration",
            field=models.CharField(
                choices=[("Y", "อพยพ"), ("N", "ไม่อพยพ"), ("S", "อพยพตามฤดูกาล")],
                default="N",
                max_length=1,
                verbose_name="การอพยพ",
            ),
        ),
    ]
