# Generated by Django 5.1.1 on 2024-09-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_habitat_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="food_source",
            field=models.CharField(
                choices=[
                    ("N", "จากธรรมชาติ"),
                    ("F", "เพาะเลี้ยง"),
                    ("S", "ซื้อจากร้านค้า"),
                ],
                default="N",
                max_length=1,
                verbose_name="แหล่งอาหาร",
            ),
        ),
    ]
