# Generated by Django 5.1.1 on 2024-09-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_food_food_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="food_source",
            field=models.CharField(
                choices=[
                    ("SUR", "บนผิวน้ำ"),
                    ("DEE", "น้ำลึก"),
                    ("SHA", "น้ำตื้น"),
                    ("BOT", "พื้นดิน"),
                ],
                default="SUR",
                max_length=3,
                verbose_name="แหล่งอาหาร",
            ),
        ),
    ]
