# Generated by Django 5.1.1 on 2024-09-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_food_food_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fish",
            name="image",
            field=models.ImageField(upload_to="fishimage", verbose_name="รูปปลา"),
        ),
    ]
